# Generated by Django 5.1.2 on 2024-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessToken',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tokenExpiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
