# Generated by Django 5.1.2 on 2024-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPIs', '0002_user_accesstoken_user_creationdate_user_refreshtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessToken',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
